package com.example.myassignment2

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.os.Handler
import android.widget.Button
import android.widget.ImageView
import android.widget.ProgressBar
import android.widget.Toast
import androidx.activity.enableEdgeToEdge

class MainActivity2 : AppCompatActivity() {

    private var EatPercentage = 50
    private var FunPercentage = 50
    private var CleanPercentage = 50
    private var isThePetDead = false

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_main2)

      //Declare
        val imageView2 = findViewById<ImageView>(R.id.imageView2)
        val imageView3 = findViewById<ImageView>(R.id.imageView3)
        val Fun = findViewById<Button>(R.id.Fun)
        val Eat = findViewById<Button>(R.id.Eat)
        val Clean = findViewById<Button>(R.id.Clean)

        imageView3.setImageResource(R.drawable.chibi_awake_dog)

        Fun.setOnClickListener {

            Toast.makeText(this,"Fun Clicked",Toast.LENGTH_SHORT).show()//To show toast

            if (!isThePetDead) {

                imageView3.setImageResource(R.drawable.chibi_playing_with_friend_dog)

                if (FunPercentage < 100) FunPercentage += 5
                updateStatus()
            }
        }
        Eat.setOnClickListener{

            Toast.makeText(this,"Eat Clicked",Toast.LENGTH_SHORT).show()

            if (!isThePetDead) {

                imageView3.setImageResource(R.drawable.chibi_eating_dog)

                if (EatPercentage < 100) EatPercentage += 5
                upadateStatus()
                    }
                }
        Clean.setOnClickListener{

            Toast.makeText(this,"Clean Clicked",Toast.LENGTH_SHORT).show()

            if (!isThePetDead) {

                imageView3.setImageResource(R.drawable.chibi_hungry_dog)
                if (CleanPercentage < 100) CleanPercentage += 5
                updateStatus()
            }
        }
    }

    private fun updateStatus() {
        TODO("Not yet implemented")
    }

    private fun upadateStatus() {
        findViewById<ProgressBar>(R.id.progressBarFun).progress = FunPercentage
        findViewById<ProgressBar>(R.id.progressBarEat).progress = EatPercentage
        findViewById<ProgressBar>(R.id.progressBarClean).progress = CleanPercentage

        if (EatPercentage <20 && !isThePetDead) {
            petIsDead()
            if (FunPercentage < 20 && ! isThePetDead) {
                petIsDead()
                if (CleanPercentage <20 && !isThePetDead) {
                    petIsDead()
                }
            }
        }
    }
    private fun petIsDead() {

        findViewById<ImageView>(R.id.imageView3). apply {
            visibility = ImageView.VISIBLE
            setImageResource(R.drawable.chibi_sleeping_dog)
        }
        isThePetDead = true

        Handler().postDelayed({

            FunPercentage = 100
            EatPercentage = 100
            CleanPercentage = 100

            findViewById<ImageView>(R.id.imageView3).visibility = ImageView.GONE
            findViewById<ProgressBar>(R.id.progressBarFun).progress = FunPercentage
            findViewById<ProgressBar>(R.id.progressBarEat).progress = EatPercentage
            findViewById<ProgressBar>(R.id.progressBarClean).progress = CleanPercentage
        },1000)
    }
}
